name: build

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1
    
      - name: Build the Docker image
        env:
          IMAGE_VERSION: $( echo ${GITHUB_REF#"refs/tags/"} )
        run: docker build . --file Dockerfile
          --tag docker.pkg.github.com/rebilly/docker-mailcatcher/mailcatcher:latest

      - name: Login to register
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin

      - name: Push the Docker image
        run: docker push docker.pkg.github.com/rebilly/docker-mailcatcher/mailcatcher:latest
