name: build

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      username: ${{ github.actor }}
      version: $( echo ${GITHUB_REF#"refs/tags/"} )
 
    steps:
      - uses: actions/checkout@v1
    
      - name: Build the Docker image
        run: docker build . --file Dockerfile
          --tag docker.pkg.github.com/rebilly/docker-mailcatcher/mailcatcher:${version}
          --tag docker.pkg.github.com/rebilly/docker-mailcatcher/mailcatcher:latest

      - name: Login to register
        run: docker login docker.pkg.github.com -u ${username} -p ${repo_token}

      - name: Push the Docker image
        run: docker push docker.pkg.github.com/rebilly/docker-mailcatcher/mailcatcher:${version}
