name: build

on:
  release:
    types: [published, created, edited]

jobs:

  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1
    
      - name: Build the Docker image
        run: docker build . --file Dockerfile
          --tag docker.pkg.github.com/rebilly/docker-mailcatcher/mailcatcher:${{ github.ref }}
          --tag docker.pkg.github.com/rebilly/docker-mailcatcher/mailcatcher:latest

      - name: Push the Docker image
        run: docker push docker.pkg.github.com/rebilly/docker-mailcatcher/mailcatcher:${{ github.ref }}
